const { contextBridge, ipcRenderer } = require('electron');

// Single, safe bridge for the renderer (billing.html).
contextBridge.exposeInMainWorld('billingAPI', {
  isElectron: true,
  load:           ()       => ipcRenderer.invoke('data:load'),
  save:           (text)   => ipcRenderer.invoke('data:save', text),
  where:          ()       => ipcRenderer.invoke('data:where'),
  reveal:         ()       => ipcRenderer.invoke('data:reveal'),
  linkExisting:   ()       => ipcRenderer.invoke('data:linkExisting'),
  createExternal: (text)   => ipcRenderer.invoke('data:createExternal', text),
  useDefault:     (text)   => ipcRenderer.invoke('data:useDefault', text),
  exportData:     (text)   => ipcRenderer.invoke('data:export', text),
  exportPDF:      (name)   => ipcRenderer.invoke('doc:pdf', name),
  importData:     ()       => ipcRenderer.invoke('data:import'),
  revealBackups:  ()       => ipcRenderer.invoke('data:revealBackups'),
  deviceId:       ()       => ipcRenderer.invoke('device:id'),
  journalAppend:  (lines)  => ipcRenderer.invoke('journal:append', lines),
  listBackups:    ()       => ipcRenderer.invoke('backups:list'),
  snapshotBackup: (label)  => ipcRenderer.invoke('backups:snapshot', label),
  restoreBackup:  (name)   => ipcRenderer.invoke('backups:restore', name),
  licenseStatus:  ()       => ipcRenderer.invoke('license:status'),
  licenseActivate:(key)    => ipcRenderer.invoke('license:activate', key),
  licenseDeactivate: ()    => ipcRenderer.invoke('license:deactivate'),
  syncStatus:     ()       => ipcRenderer.invoke('sync:status'),
  syncConnect:    (name)   => ipcRenderer.invoke('sync:connect', name),
  syncDisconnect: ()       => ipcRenderer.invoke('sync:disconnect'),
  syncPush:       ()       => ipcRenderer.invoke('sync:push'),
  syncPull:       ()       => ipcRenderer.invoke('sync:pull'),
  syncCommitPull: (cur)    => ipcRenderer.invoke('sync:commitPull', cur),
  syncSnapshot:   (text)   => ipcRenderer.invoke('sync:snapshot', text),
  syncRestore:    ()       => ipcRenderer.invoke('sync:restore'),
  aiStatus:       ()       => ipcRenderer.invoke('ai:status'),
  aiInfer:        (text)   => ipcRenderer.invoke('ai:infer', text),
  importTor:      (path)   => ipcRenderer.invoke('ai:importTor', path),
  revealAiFolder: ()       => ipcRenderer.invoke('ai:reveal'),
  onMenuExport:   (cb)     => ipcRenderer.on('menu:export', cb),
  onMenuImport:   (cb)     => ipcRenderer.on('menu:import', cb),
  onQuitFlush:    (cb)     => ipcRenderer.on('app:quitFlush', cb),
  quitFlushDone:  ()       => ipcRenderer.send('app:quitFlushDone')
});
